version: "3.9"
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: transactional
      MYSQL_USER: transactional
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
